apiVersion: v1
kind: Secret
metadata:
  name: uvp-secrets
  namespace: unified-cctv
type: Opaque
stringData:
  token-secret: CHANGE-ME
  internal-secret: CHANGE-ME
  relay-internal-pass: CHANGE-ME
  s3-access-key: CHANGE-ME
  s3-secret-key: CHANGE-ME
  police-onvif-pass: CHANGE-ME
  muni-api-pass: CHANGE-ME
