apiVersion: v1
kind: Secret
metadata:
  name: uvp-secrets
  namespace: unified-cctv
type: Opaque
stringData:
  token-secret: "change-me-token"
  internal-secret: "change-me-internal"
  relay-internal-pass: "change-me-relay"
  s3-access-key: "6653bfa5336a2ecee306b729a3f1b95aa2597ca5"
  s3-secret-key: "rFqHEcIOoF2IXfyJZssYQD7Xysg8iix1SJmaGYtF6s="
  police-onvif-pass: CHANGE-ME
  muni-api-pass: CHANGE-ME
