apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: unified-cctv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 200Gi
